export const memberData = [
  {
    uid: 0,
    account: 'jacky',
    memberType: 'normalMember',
    createTime: '2021-08-10',
  },
  {
    uid: 1,
    account: 'John Smith',
    memberType: 'normalMember',
    createTime: '2021-12-25',
  },
  {
    uid: 2,
    account: 'Emily Johnson',
    memberType: 'normalMember',
    createTime: '2022-04-03',
  },
  {
    uid: 3,
    account: 'Michael Williams',
    memberType: 'normalMember',
    createTime: '2021-11-18',
  },
  {
    uid: 4,
    account: 'Jessica Brown',
    memberType: 'normalMember',
    createTime: '2022-02-09',
  },
  {
    uid: 5,
    account: 'Daniel Johnson',
    memberType: 'normalMember',
    createTime: '2022-06-22',
  },
  {
    uid: 6,
    account: 'Sophia Jones',
    memberType: 'normalMember',
    createTime: '2022-05-14',
  },
  {
    uid: 7,
    account: 'Olivia Williams',
    memberType: 'normalMember',
    createTime: '2021-10-06',
  },
  {
    uid: 8,
    account: 'James Davis',
    memberType: 'normalMember',
    createTime: '2023-01-31',
  },
  {
    uid: 9,
    account: 'Emma Smith',
    memberType: 'normalMember',
    createTime: '2021-09-05',
  },
  {
    uid: 10,
    account: 'William Johnson',
    memberType: 'normalMember',
    createTime: '2023-05-18',
  },
  {
    uid: 11,
    account: 'Liam Smith',
    memberType: 'normalMember',
    createTime: '2023-02-28',
  },
  {
    uid: 12,
    account: 'Olivia Johnson',
    memberType: 'normalMember',
    createTime: '2023-06-09',
  },
  {
    uid: 13,
    account: 'Noah Smith',
    memberType: 'normalMember',
    createTime: '2023-04-16',
  },
  {
    uid: 14,
    account: 'Ava Davis',
    memberType: 'normalMember',
    createTime: '2021-11-08',
  },
  {
    uid: 15,
    account: 'Isabella Johnson',
    memberType: 'normalMember',
    createTime: '2022-09-20',
  },
  {
    uid: 16,
    account: 'Ethan Davis',
    memberType: 'normalMember',
    createTime: '2022-12-10',
  },
  {
    uid: 17,
    account: 'Mia Brown',
    memberType: 'normalMember',
    createTime: '2021-07-19',
  },
  {
    uid: 18,
    account: 'Sophia Williams',
    memberType: 'normalMember',
    createTime: '2022-08-03',
  },
  {
    uid: 19,
    account: 'Emma Davis',
    memberType: 'normalMember',
    createTime: '2021-10-15',
  },
  {
    uid: 20,
    account: 'Oliver Johnson',
    memberType: 'normalMember',
    createTime: '2021-12-02',
  },
  {
    uid: 21,
    account: 'Aiden Smith',
    memberType: 'normalMember',
    createTime: '2023-05-27',
  },
  {
    uid: 22,
    account: 'Sophia Smith',
    memberType: 'normalMember',
    createTime: '2022-07-17',
  },
  {
    uid: 23,
    account: 'Lucas Johnson',
    memberType: 'normalMember',
    createTime: '2021-09-12',
  },
  {
    uid: 24,
    account: 'Emma Davis',
    memberType: 'normalMember',
    createTime: '2022-11-30',
  },
  {
    uid: 25,
    account: 'Ava Johnson',
    memberType: 'normalMember',
    createTime: '2021-08-28',
  },
  {
    uid: 26,
    account: 'Noah Smith',
    memberType: 'normalMember',
    createTime: '2023-04-06',
  },
  {
    uid: 27,
    account: 'Isabella Johnson',
    memberType: 'normalMember',
    createTime: '2021-07-07',
  },
  {
    uid: 28,
    account: 'Liam Smith',
    memberType: 'normalMember',
    createTime: '2023-03-23',
  },
  {
    uid: 29,
    account: 'Oliver Williams',
    memberType: 'normalMember',
    createTime: '2022-01-11',
  },
  {
    uid: 30,
    account: 'Ethan Davis',
    memberType: 'normalMember',
    createTime: '2022-10-27',
  },
  {
    uid: 31,
    account: 'Ava Johnson',
    memberType: 'normalMember',
    createTime: '2023-07-14',
  },
  {
    uid: 32,
    account: 'Sophia Smith',
    memberType: 'normalMember',
    createTime: '2021-09-26',
  },
  {
    uid: 33,
    account: 'Michael Scott',
    memberType: 'seniorMember',
    createTime: '2021-08-10',
  },
  {
    uid: 34,
    account: 'Angela Martin',
    memberType: 'seniorMember',
    createTime: '2021-12-25',
  },
  {
    uid: 35,
    account: 'Dwight Schrute',
    memberType: 'seniorMember',
    createTime: '2022-04-03',
  },
  {
    uid: 36,
    account: 'Pam Beesly',
    memberType: 'seniorMember',
    createTime: '2021-11-18',
  },
  {
    uid: 37,
    account: 'Jim Halpert',
    memberType: 'seniorMember',
    createTime: '2022-02-09',
  },
  {
    uid: 38,
    account: 'Ryan Howard',
    memberType: 'seniorMember',
    createTime: '2022-06-22',
  },
  {
    uid: 39,
    account: 'Kelly Kapoor',
    memberType: 'seniorMember',
    createTime: '2022-05-14',
  },
  {
    uid: 40,
    account: 'Stanley Hudson',
    memberType: 'seniorMember',
    createTime: '2021-10-06',
  },
  {
    uid: 41,
    account: 'Kevin Malone',
    memberType: 'seniorMember',
    createTime: '2023-01-31',
  },
  {
    uid: 42,
    account: 'Meredith Palmer',
    memberType: 'seniorMember',
    createTime: '2021-09-05',
  },
  {
    uid: 43,
    account: 'Creed Bratton',
    memberType: 'seniorMember',
    createTime: '2023-05-18',
  },
  {
    uid: 44,
    account: 'Oscar Martinez',
    memberType: 'seniorMember',
    createTime: '2023-02-28',
  },
  {
    uid: 45,
    account: 'Phyllis Smith',
    memberType: 'seniorMember',
    createTime: '2023-06-09',
  },
  {
    uid: 46,
    account: 'Andy Bernard',
    memberType: 'seniorMember',
    createTime: '2023-04-16',
  },
  {
    uid: 47,
    account: 'Toby Flenderson',
    memberType: 'seniorMember',
    createTime: '2021-11-08',
  },
  {
    uid: 48,
    account: 'Kelly Clarkson',
    memberType: 'honoraryMember',
    createTime: '2021-08-10',
  },
  {
    uid: 49,
    account: 'John Legend',
    memberType: 'honoraryMember',
    createTime: '2021-12-25',
  },
  {
    uid: 50,
    account: 'Adele Adkins',
    memberType: 'honoraryMember',
    createTime: '2022-04-03',
  },
  {
    uid: 51,
    account: 'Taylor Swift',
    memberType: 'honoraryMember',
    createTime: '2021-11-18',
  },
  {
    uid: 52,
    account: 'Beyoncé Knowles',
    memberType: 'honoraryMember',
    createTime: '2022-02-09',
  },
  {
    uid: 53,
    account: 'Ed Sheeran',
    memberType: 'honoraryMember',
    createTime: '2022-06-22',
  },
  {
    uid: 54,
    account: 'Rihanna Fenty',
    memberType: 'honoraryMember',
    createTime: '2022-05-14',
  },
  {
    uid: 55,
    account: 'Justin Bieber',
    memberType: 'honoraryMember',
    createTime: '2021-10-06',
  },
];

export const EventData = [
  {
    date: '2022-08-12',
    join: 6,
    totalJoin: 21,
    imgData: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFOLEpMK2zHe3EVmWUlEipk57ongbc7kif0A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMs9dsNtWEwE0mj1lYXzb3kjZmEImwwwr6aA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3UUWCvktdONcSd5Yo72y8nujJaeMqh6_l5Q&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyS4vfeQB5UUy9z4uTcGRIg25DnsPHQOn5Yw&usqp=CAU',
    ],
  },
  {
    date: '2022-08-17',
    join: 10,
    totalJoin: 25,
    imgData: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSwghmqnXOm7elulMdNSKYNOAOt3ePpCTVLg&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfZH-4y0IzpSfgyTT0fnjs8iC0ck8AubNrSg&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFgoLGKiTPzL4L8sayr2SnI7cA1t1xknBy0A&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNDcteok2h0p0vqC2u-1YZ6u64-K6x8PazFA&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkywvb8wvEuZmXMW8Fxa88UysmFav4Tb85cw&usqp=CAU',
    ],
  },
  {
    date: '2022-08-21',
    join: 15,
    totalJoin: 20,
    imgData: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS-qUTmdxk-Z0-2F5F8MU87EAJXAKgwG28wQ&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBI9rp3H4BUI7vhg1TcRPZGrgZuo974w3vzw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX4qqoD9AqmBpPzDvxJfsEG2cLJBrk2S9mCQ&usqp=CAU',
    ],
  },
  {
    date: '2022-08-29',
    join: 12,
    totalJoin: 15,
    imgData: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT_wxpZ4FYtYZk4JA9pmEcQ_KcmW-4gPXYxg&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPzLiHducs32XAPfvMc6S7aJzDlgZm6JrtKw&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdDR4_939DW1dySvPUQd3_vAZ4voGeU5xX8w&usqp=CAU',
    ],
  },
];
